# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'L2_toroyanseda' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'Alamofire'
pod 'AlamofireObjectMapper'
  # Pods for L2_toroyanseda

end
